rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
  - jruby
  - jruby-head
  - rbx

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

bundler_args: --without guard docs
before_install:
  - gem install bundler -v '= 1.5.1'
